# Generated by Django 5.2.7 on 2025-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bird', 'bird'), ('rabbit', 'rabbit'), ('fish', 'fish')], max_length=10)),
                ('name', models.TextField()),
                ('discription', models.TextField()),
                ('pet_price', models.IntegerField()),
                ('pet_image', models.ImageField(upload_to='pet_image/')),
            ],
        ),
    ]
