# Generated by Django 5.2.7 on 2025-11-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdetails',
            old_name='discription',
            new_name='description',
        ),
    ]
