# Generated by Django 6.0 on 2026-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdetails',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petdetails',
            name='category',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish')], max_length=10),
        ),
        migrations.AlterField(
            model_name='petdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='petdetails',
            name='pet_price',
            field=models.PositiveIntegerField(),
        ),
    ]
