# Generated by Django 6.0 on 2026-01-13 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
